<?php
declare(strict_types=1);
function movidesk_settings():array{$file=dirname(__DIR__,2).'/private/newsiga-movidesk.php';if(!is_file($file))throw new RuntimeException('A integração com o Movidesk ainda não foi configurada.');$settings=require $file;if(!is_array($settings)||empty($settings['token']))throw new RuntimeException('A configuração do Movidesk está incompleta.');return $settings;}
function movidesk_get(string $resource,array $parameters=[]):array{$m=movidesk_settings();$base=rtrim((string)($m['base_url']??'https://api.movidesk.com/public/v1'),'/');$parameters=['token'=>(string)$m['token']]+$parameters;$requestUrl=$base.'/'.ltrim($resource,'/').'?'.http_build_query($parameters,'','&',PHP_QUERY_RFC3986);$ch=curl_init($requestUrl);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_TIMEOUT=>(int)($m['timeout']??30),CURLOPT_HTTPHEADER=>['Accept: application/json'],CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2]);$body=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$curlError=curl_error($ch);curl_close($ch);if($body===false)throw new RuntimeException('Conexão: '.($curlError?:'falha desconhecida').'.');if($status!==200){$safeMessage='';$decoded=json_decode((string)$body,true);if(is_array($decoded))$safeMessage=(string)($decoded['error']['message']??$decoded['message']??'');throw new RuntimeException('Movidesk respondeu HTTP '.$status.($safeMessage!==''?': '.substr($safeMessage,0,180):'.'));}$data=json_decode((string)$body,true);if(!is_array($data))throw new RuntimeException('O Movidesk retornou uma resposta inválida.');return $data;}
function movidesk_contracts(bool $activeOnly=true):array{$contracts=movidesk_get('timeAgreement',['$select'=>'id,name,isActive,contractedHours,renewalDay,accumulateUnusedHours,differentiateHoursFranchise,differentiateHoursConsumption','$orderby'=>'name asc']);if(!$activeOnly)return $contracts;return array_values(array_filter($contracts,static fn(array $contract):bool=>($contract['isActive']??false)===true));}
function movidesk_consumption(string $name,string $start,string $end):array{return movidesk_get('timeAgreementConsumption',['name'=>$name,'startPeriod'=>$start,'endPeriod'=>$end]);}
function movidesk_ticket(int $id):array{return movidesk_get('tickets',['id'=>$id,'$select'=>'id,type,subject,category,urgency,status,baseStatus,createdDate,lastUpdate,serviceFull','$expand'=>'actions']);}
function movidesk_cached(string $resource,array $parameters,int $ttl=300):array{$dir=dirname(__DIR__,2).'/private/movidesk-cache';if(!is_dir($dir)&&!@mkdir($dir,0700,true)&&!is_dir($dir))return movidesk_get($resource,$parameters);$file=$dir.'/'.hash('sha256',$resource.'|'.json_encode($parameters)).'.json';if(is_file($file)&&filemtime($file)>time()-$ttl){$cached=json_decode((string)file_get_contents($file),true);if(is_array($cached))return $cached;}$data=movidesk_get($resource,$parameters);@file_put_contents($file,json_encode($data,JSON_UNESCAPED_UNICODE),LOCK_EX);@chmod($file,0600);return $data;}
function movidesk_consumption_cached(string $name,string $start,string $end,int $ttl=300):array{return movidesk_cached('timeAgreementConsumption',['name'=>$name,'startPeriod'=>$start,'endPeriod'=>$end],$ttl);}
function movidesk_ticket_cached(int $id,int $ttl=300):array{return movidesk_cached('tickets',['id'=>$id,'$select'=>'id,type,subject,category,urgency,status,baseStatus,createdDate,lastUpdate,serviceFull','$expand'=>'actions'],$ttl);}
function movidesk_contract_cached(string $name,int $ttl=600):array{return movidesk_cached('timeAgreement',['name'=>$name,'$expand'=>'typeActivities,timeTypeConsumption'],$ttl);}
function movidesk_ticket_clients_cached(int $id,int $ttl=3600):array{return movidesk_cached('tickets',['id'=>$id,'$select'=>'id,subject','$expand'=>'clients'],$ttl);}
function movidesk_person_relationships_cached(string $id,int $ttl=3600):array{return movidesk_cached('persons',['id'=>$id,'$select'=>'id,businessName,personType,profileType','$expand'=>'relationships'],$ttl);}
