<?php
declare(strict_types=1);
function portal_time_hours(string $time):float{$p=array_map('intval',explode(':',$time));return($p[0]??0)+(($p[1]??0)/60)+(($p[2]??0)/3600);}
function portal_entry_hours(array $entry):float{$workTime=(string)($entry['workTime']??'');if(preg_match('/^\d{1,3}:\d{2}(?::\d{2})?$/',$workTime))return portal_time_hours($workTime);$start=(string)($entry['periodStart']??'');$end=(string)($entry['periodEnd']??'');if(preg_match('/^\d{2}:\d{2}:\d{2}$/',$start)&&preg_match('/^\d{2}:\d{2}:\d{2}$/',$end)){$startSeconds=(int)round(portal_time_hours($start)*3600);$endSeconds=(int)round(portal_time_hours($end)*3600);if($endSeconds>$startSeconds)return($endSeconds-$startSeconds)/3600;}return 0.0;}
function portal_bills_by_consumption(string $companySlug):bool{return in_array($companySlug,['pernambuco-quimica','fiabesa-guararapes-sa'],true);}
function portal_has_minimum_package(string $companySlug):bool{return $companySlug==='dragao';}
function portal_period_is_closed(array $consumption):bool{return isset($consumption['id'])&&(string)$consumption['id']!==''&&(string)$consumption['id']!=='0';}
function portal_duration(float $hours):string{$minutes=max(0,(int)round($hours*60));return sprintf('%02dh%02d',intdiv($minutes,60),$minutes%60);}
function portal_period(string $month):array{if(!preg_match('/^\d{4}-\d{2}$/',$month))$month=date('Y-m');return[$month,$month.'-01T00:00:00',date('Y-m-t',strtotime($month.'-01')).'T23:59:59'];}
function portal_consumption(string $contractName,string $month):array{[$month,$start,$end]=portal_period($month);$definition=movidesk_contract_cached($contractName);if(isset($definition[0])&&is_array($definition[0]))$definition=$definition[0];if(($definition['isActive']??true)!==true)throw new RuntimeException('Contrato inativo no Movidesk.');$data=movidesk_consumption_cached($contractName,$start,$end);if(isset($data[0])&&is_array($data[0]))$data=$data[0];$appointments=$data['timeAppointments']??[];$sum=0.0;foreach($appointments as $entry)$sum+=portal_entry_hours($entry);$officialConsumed=(float)($data['consumedHours']??0);if($officialConsumed>0)$sum=$officialConsumed;return['month'=>$month,'definition'=>$definition,'raw'=>$data,'appointments'=>$appointments,'consumed'=>$sum];}
function portal_group_tickets(array $appointments):array{$tickets=[];foreach($appointments as $entry){$number=(string)($entry['ticketNumber']??'');if($number==='')continue;if(!isset($tickets[$number]))$tickets[$number]=['number'=>$number,'hours'=>0.0,'date'=>(string)($entry['date']??''),'activity'=>(string)($entry['activity']??''),'work_types'=>[],'hours_by_type'=>[],'segments'=>[],'responsibles'=>[]];$hours=portal_entry_hours($entry);$tickets[$number]['hours']+=$hours;$type=(string)($entry['workTypeName']??'');if($type!==''){$tickets[$number]['work_types'][$type]=true;$tickets[$number]['hours_by_type'][$type]=($tickets[$number]['hours_by_type'][$type]??0)+$hours;$tickets[$number]['segments'][]=['type'=>$type,'hours'=>$hours];}$responsible=(string)($entry['createdBy']['businessName']??'');if($responsible!=='')$tickets[$number]['responsibles'][$responsible]=true;}usort($tickets,static fn($a,$b)=>strcmp($a['date'],$b['date'])?:strcmp($a['number'],$b['number']));return array_values($tickets);}
function portal_ticket_values(array $tickets,float $contracted,float $baseRate,float $excessRate):array{$remaining=max(0,$contracted);$totalExtra=0.0;foreach($tickets as &$ticket){$covered=min($remaining,$ticket['hours']);$remaining-=$covered;$ticket['covered_hours']=$covered;$ticket['extra_hours']=max(0,$ticket['hours']-$covered);$ticket['value']=($covered*$baseRate)+($ticket['extra_hours']*$excessRate);$totalExtra+=$ticket['extra_hours']*$excessRate;}unset($ticket);return[$tickets,$totalExtra];}
function portal_differentiated_values(array $tickets,array $definition):array{$rules=[];foreach(($definition['typeActivities']??[])as $rule){$type=(string)($rule['workingTimeType']??'');if($type==='')continue;$rules[$type]=['franchise'=>(float)($rule['franchise']??0),'rate'=>(float)($rule['value']??0),'excess_rate'=>(float)($rule['valueExceededHour']??0)];}$remaining=array_map(static fn(array $rule):float=>max(0,$rule['franchise']),$rules);$typeTotals=array_fill_keys(array_keys($rules),0.0);$total=0.0;foreach($tickets as &$ticket){$ticket['value']=0.0;$ticket['covered_hours']=0.0;$ticket['extra_hours']=0.0;foreach(($ticket['segments']??[])as $segment){$type=(string)$segment['type'];$hours=(float)$segment['hours'];$rule=$rules[$type]??null;if(!$rule)continue;$covered=min($remaining[$type]??0,$hours);$remaining[$type]=max(0,($remaining[$type]??0)-$covered);$extra=max(0,$hours-$covered);$extraRate=$rule['excess_rate']>0?$rule['excess_rate']:$rule['rate'];$segmentValue=round(($covered*$rule['rate'])+($extra*$extraRate),2);$ticket['covered_hours']+=$covered;$ticket['extra_hours']+=$extra;$ticket['value']+=$segmentValue;$typeTotals[$type]+=$segmentValue;}$ticket['value']=round($ticket['value'],2);$total+=$ticket['value'];}unset($ticket);return[$tickets,round($total,2),$rules,$typeTotals];}
function portal_ticket_requester_department(int $ticketId):array{$ticket=movidesk_ticket_clients_cached($ticketId);if(isset($ticket[0])&&is_array($ticket[0]))$ticket=$ticket[0];$clients=$ticket['clients']??[];$selected=null;foreach($clients as $client){if(($client['isDeleted']??false)===true)continue;$selected=$client;if(strtolower((string)($client['role']??''))==='cliente')break;}if(!$selected)return['requester'=>'Não identificado','department'=>'Não identificado'];$requester=(string)($selected['businessName']??'Não identificado');$department=(string)($selected['organization']['businessName']??'');$personId=(string)($selected['id']??'');if($personId!==''){try{$person=movidesk_person_relationships_cached($personId);if(isset($person[0])&&is_array($person[0]))$person=$person[0];$relationships=$person['relationships']??[];if($relationships){$name=(string)($relationships[0]['name']??'');if($name!==''){$parts=array_values(array_filter(array_map('trim',explode('/',$name))));$department=(string)(end($parts)?:$name);}}}catch(Throwable $e){error_log('Newsiga departamento pessoa '.$personId.': '.$e->getMessage());}}return['requester'=>$requester,'department'=>$department?:'Não identificado'];}
function portal_department_totals(array &$tickets):array{$departments=[];foreach($tickets as &$ticket){$identity=portal_ticket_requester_department((int)$ticket['number']);$ticket['requester']=$identity['requester'];$ticket['department']=$identity['department'];$ticket['responsibles']=[$identity['requester'].' · '.$identity['department']=>true];$key=$identity['department'];if(!isset($departments[$key]))$departments[$key]=['name'=>$key,'hours'=>0.0,'value'=>0.0];$departments[$key]['hours']+=(float)$ticket['hours'];$departments[$key]['value']+=(float)$ticket['value'];}unset($ticket);uasort($departments,static fn($a,$b)=>$b['hours']<=>$a['hours']);return array_values($departments);}
function portal_month_label(string $month):string{$names=['01'=>'janeiro','02'=>'fevereiro','03'=>'março','04'=>'abril','05'=>'maio','06'=>'junho','07'=>'julho','08'=>'agosto','09'=>'setembro','10'=>'outubro','11'=>'novembro','12'=>'dezembro'];[$year,$number]=explode('-',$month);return($names[$number]??$number).' de '.$year;}
if(basename((string)($_SERVER['SCRIPT_NAME']??''))==='relatorio.php'){ob_start(static function(string $html):string{global $company,$tickets,$consumed;if(($company['slug']??'')!=='pernambuco-quimica'||!is_array($tickets)||!$tickets)return$html;try{$departments=portal_department_totals($tickets);}catch(Throwable $e){error_log('Newsiga relatório por departamento: '.$e->getMessage());return$html;}if(!$departments)return$html;$rows='';foreach($departments as $department){$percent=$consumed>0?($department['hours']/$consumed)*100:0;$rows.='<tr><td><strong>'.e($department['name']).'</strong></td><td>'.portal_duration((float)$department['hours']).'</td><td>'.number_format($percent,0,',','.').'%</td><td class="money">R$ '.number_format((float)$department['value'],2,',','.').'</td></tr>';}$section='<section class="section department-summary"><h2>CONSUMO POR SETOR</h2><div class="table-wrap"><table><thead><tr><th>SETOR</th><th>HORAS</th><th>%</th><th class="money">VALOR</th></tr></thead><tbody>'.$rows.'</tbody></table></div></section>';$marker='<section class="section"><h2>DISTRIBUIÇÃO DOS ATENDIMENTOS</h2>';return str_replace($marker,$section.$marker,$html);});}
if(basename((string)($_SERVER['SCRIPT_NAME']??''))==='relatorio.php'){ob_start(static function(string $html):string{return preg_replace('~<div class="grand"><span>Total do período</span><strong>(.*?)</strong>(?:<small.*?</small>)?</div>~s','<div class="grand"><span>Total do período</span><span style="text-align:right"><strong>$1</strong><small style="display:block;margin-top:4px;color:#89968f;font-size:10px;font-weight:400">Sem impostos</small></span></div>',$html,1)??$html;});}
